#!/usr/bin/env bash
# PinToMindOS Setup script
# Installs a minimal desktop environment, which only runs the pintomind-player Electron 
# app in fullscreen mode.
# Also sets up automatic login for the pi user.
# Written by Zolve for Favo AS
########


# Source error handling, leave this in place
set -x
set -e

source /common.sh
install_cleanup_trap

# Transfer files
unpack /filesystem/home/pi /home/"${BASE_USER}" "${BASE_USER}"
unpack /filesystem/home/root /root root
unpack /filesystem/boot /boot
unpack /filesystem/etc /etc

# Disable screen timeout. Note that 0 is enabled, 1 is disabled
raspi-config nonint do_blanking 1

# Prevents an SSL error on first startup of pintomind-player
fake-hwclock save

# Install our minimal desktop environment
apt-get install -y xserver-xorg libgles2-mesa libgles2-mesa-dev xorg-dev pciutils \
	xinput pulseaudio pulseaudio-utils metacity xinit fuse x11-xserver-utils plymouth \
        plymouth-themes pix-plym-splash bluetooth bluez libbluetooth-dev libudev-dev \
        libusb-1.0-0-dev libcap2-bin

# Install Node, for the BLE bridge
mkdir -p /etc/apt/keyrings
curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_18.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list
apt update
apt install -y nodejs

# Enable Plymouth to get a nice boot screen
plymouth-set-default-theme -R spinner
# Uncomment the next line to enable image on startup
cp /home/pi/splash-screen.png /usr/share/plymouth/themes/spinner/header-image.png
echo "disable_splash=1" >> /boot/config.txt
sed -i /boot/cmdline.txt -e 's/$/ quiet splash plymouth.ignore-serial-consoles/'

# By default, tty1 is displayed during boot. If we want to hide boot messages, we can send them to tty3 instead
sed -i /boot/cmdline.txt -e 's/tty1/tty3/'

# Enable automatic login
sed -i "/lib/systemd/system/getty@.service" -e 's:ExecStart=.*$:ExecStart=-/sbin/agetty --skip-login --nonewline --noissue --autologin pi --noclear %I $TERM:'

# Automatically boot to desktop if we are in GeTTY
echo '[[ -z $DISPLAY && $XDG_VTNR -eq 1 ]] && exec startx -- -quiet' >> /home/pi/.bashrc
# Use this line instead if we want to hide the cursor
# echo '[[ -z $DISPLAY && $XDG_VTNR -eq 1 ]] && exec startx -- -quiet -nocursor' >> /home/pi/.bashrc

# Enable NetworkManager, as it is easier to use it to configure Wi-Fi
systemctl enable NetworkManager
systemctl enable bluetooth-power

# Configure the BLE bridge
systemctl disable bluetooth
setcap cap_net_raw+eip $(eval readlink -f `command -v node`)
cd /home/pi/ble-bridge
sudo -u pi npm i
systemctl enable ble-bridge

# Unpack root at the end, so files are modified before
unpack /filesystem/root /